version: '3.8'

services:
    pcs-bot:
        build:
            context: ../..
            dockerfile: Dockerfile
        image: pcs-bot:dev 
        environment:
            BOT_CHANNEL: # name of command channel
            BOT_TOKEN: # server bot token
            GUILD_TOKEN: # guild id
        volumes:
            - ../../src:/app
