version: '3.8'

services:
    pcs-bot:
        image: acmfsu/pcs-bot:latest
        environment:
            BOT_CHANNEL: # server bot control channel
            BOT_TOKEN: # server bot token
            GUILD_TOKEN: # guild id
        deploy:
            restart_policy:
                max_attempts: 10
            update_config:
                delay: 5s
                failure_action: rollback
